### ISSUE TITLE
OpenAPI 3.0.0 petstore.yaml definition is not supported

### ISSUE THREAD

**Issue by steveeJ** [Mermade/openapi-codegen#15]
* node --version: v6.12.2
* openapi-codegen at fda84f88129f3ed6803285772bc888f49e256527

The command run is `cg --debug --lint --verbose nodejs defs/petstore.yaml` for the following reports.

### Null response leads to TypeError

https://github.com/OAI/OpenAPI-Specification/blob/e9c539d86f080f133aa35c3e7db33ef004496625/examples/v3.0/petstore.yaml#L47-L49

leads to 

```
{ level: 'Error',
  elementType: 'Context',
  elementId: '#/info/license',
  message: 'expected Object { name: \'MIT\' } to have property url' }
/home/steveej/.npm-packages/lib/node_modules/openapi-codegen/adaptor.js:326
            let contentType = Object.values(response.content)[0];
                                     ^

TypeError: Object.values is not a function
    at convertOperation (/home/steveej/.npm-packages/lib/node_modules/openapi-codegen/adaptor.js:326:38)
    at convertToApis (/home/steveej/.npm-packages/lib/node_modules/openapi-codegen/adaptor.js:448:33)
    at Object.transform (/home/steveej/.npm-packages/lib/node_modules/openapi-codegen/adaptor.js:786:24)
    at Object.main (/home/steveej/.npm-packages/lib/node_modules/openapi-codegen/index.js:30:13)
    at main (/home/steveej/.npm-packages/lib/node_modules/openapi-codegen/cg.js:155:19)
    at Object.<anonymous> (/home/steveej/.npm-packages/lib/node_modules/openapi-codegen/cg.js:197:4)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```

Adding some content helps to workaround this issue.

```diff
@@ -47,6 +47,7 @@ paths:
       responses:
         201:
           description: Null response
+          content: Null content
         default:
           description: unexpected error
           content:
```

### $ref usage leads to TypeError

```
/home/steveej/.npm-packages/lib/node_modules/openapi-codegen/lib/orange/downconvert.js:59
  var ref = obj.$ref;
               ^

TypeError: Cannot read property '$ref' of undefined
    at resolveReference (/home/steveej/.npm-packages/lib/node_modules/openapi-codegen/lib/orange/downconvert.js:59:16)
    at convertResponses (/home/steveej/.npm-packages/lib/node_modules/openapi-codegen/lib/orange/downconvert.js:188:24)
    at convertOperations (/home/steveej/.npm-packages/lib/node_modules/openapi-codegen/lib/orange/downconvert.js:93:17)
    at convert (/home/steveej/.npm-packages/lib/node_modules/openapi-codegen/lib/orange/downconvert.js:25:3)
    at Object.transform (/home/steveej/.npm-packages/lib/node_modules/openapi-codegen/adaptor.js:680:23)
    at Object.main (/home/steveej/.npm-packages/lib/node_modules/openapi-codegen/index.js:30:13)
    at main (/home/steveej/.npm-packages/lib/node_modules/openapi-codegen/cg.js:155:19)
    at Object.<anonymous> (/home/steveej/.npm-packages/lib/node_modules/openapi-codegen/cg.js:197:4)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
```

Being unfamiliar with the project and JS, this is where I'm stuck.

**Comment by MikeRalphson** [comment]
Hi, a few things going on here.

You should only really specify the `--lint` flag if you're the author of the definition and you expect it to pass `swagger2openapi`'s linter. This involves stylistic rules above and beyond the normal validation which is always performed.  However, if you edit the definition so all the linter errors go away, some improvements in code generation may be seen.

As you're running on Node 6.x the `--harmony` flag is required to enable certain features, including `object.values`. I've added a note to the `README.md` to this effect.

I can't see the problem regarding the `$ref` in the downconverter, but this is due to you adding a string `Null content` where an `object` is expected.

So, I would try again with an unedited petstore example, without the `--lint` flag, but with the `--harmony` option to node:

`node --harmony cg -debug --verbose nodejs https://raw.githubusercontent.com/OAI/OpenAPI-Specification/e9c539d86f080f133aa35c3e7db33ef004496625/examples/v3.0/petstore.yaml`

Please let me know how you get along.

**Comment by steveeJ** [comment]
Thanks for your suggestion! I've just upgraded to Node v9.x which alleviates this issue ;-)
