### ISSUE TITLE
Doesn't accept URL in $ref (downconverting to OAS 2.0)

### ISSUE THREAD

**Issue by alansill** [Mermade/openapi-codegen#45]
For OpenAPI input that has $ref values that point to a URL, the cg process stops, e.g. when encounterint a line like:

$ref: http://localhost:8090/openapi-local/Message.v1_0_6.yaml

it stops with:

$ cg -v -d debug ../local-test/openapi-local/openapi.yaml
Loaded config debug
Loaded definition ../local-test/openapi-local/openapi.yaml
/usr/local/lib/node_modules/openapi-codegen/lib/orange/downconvert.js:64
  keys.forEach(k => cur = cur[k]);
                             ^

TypeError: Cannot read property 'localhost:8090' of undefined
    at keys.forEach.k (/usr/local/lib/node_modules/openapi-codegen/lib/orange/downconvert.js:64:30)
    at Array.forEach (<anonymous>)
    at resolveReference (/usr/local/lib/node_modules/openapi-codegen/lib/orange/downconvert.js:64:8)
    at convertResponses (/usr/local/lib/node_modules/openapi-codegen/lib/orange/downconvert.js:189:24)
    at convertOperations (/usr/local/lib/node_modules/openapi-codegen/lib/orange/downconvert.js:93:17)
    at convert (/usr/local/lib/node_modules/openapi-codegen/lib/orange/downconvert.js:25:3)
    at Object.transform (/usr/local/lib/node_modules/openapi-codegen/adaptor.js:694:23)
    at Object.main (/usr/local/lib/node_modules/openapi-codegen/index.js:35:13)
    at main (/usr/local/lib/node_modules/openapi-codegen/cg.js:174:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/openapi-codegen/cg.js:217:4)

**Comment by MikeRalphson** [comment]
I'm unsure where your `$ref` is within your source openapi document. Is it possible to share a minimal example which displays the problem in the form of a gist?

**Comment by MikeRalphson** [comment]
Closing due to inactivity - but please feel free to reopen the issue if necessary.
