### ISSUE TITLE
Maximum call stack size exceeded with gmail api from APIs-guru/openapi-directory

### ISSUE THREAD

**Issue by FabianFrank** [Mermade/openapi-codegen#47]
When running the generator against https://github.com/APIs-guru/openapi-directory/blob/master/APIs/googleapis.com/gmail/v1/swagger.yaml it crashes with the following error:

```
$ cg typescript-node ~/Downloads/swagger.yaml

{ level: 'Error',
  elementType: 'Context',
  elementId: '#/',
  message: 'Maximum call stack size exceeded' }
/Users/fabian/.nvm/versions/node/v10.9.0/lib/node_modules/openapi-codegen/node_modules/openapi-sampler/dist/openapi-sampler.js:717
function traverse(schema, options, spec) {
                 ^

RangeError: Maximum call stack size exceeded
    at traverse (/Users/fabian/.nvm/versions/node/v10.9.0/lib/node_modules/openapi-codegen/node_modules/openapi-sampler/dist/openapi-sampler.js:717:18)
    at /Users/fabian/.nvm/versions/node/v10.9.0/lib/node_modules/openapi-codegen/node_modules/openapi-sampler/dist/openapi-sampler.js:582:43
    at Array.forEach (<anonymous>)
    at sampleObject (/Users/fabian/.nvm/versions/node/v10.9.0/lib/node_modules/openapi-codegen/node_modules/openapi-sampler/dist/openapi-sampler.js:576:36)
    at traverse (/Users/fabian/.nvm/versions/node/v10.9.0/lib/node_modules/openapi-codegen/node_modules/openapi-sampler/dist/openapi-sampler.js:782:17)
    at sampleArray (/Users/fabian/.nvm/versions/node/v10.9.0/lib/node_modules/openapi-codegen/node_modules/openapi-sampler/dist/openapi-sampler.js:446:45)
    at traverse (/Users/fabian/.nvm/versions/node/v10.9.0/lib/node_modules/openapi-codegen/node_modules/openapi-sampler/dist/openapi-sampler.js:782:17)
    at /Users/fabian/.nvm/versions/node/v10.9.0/lib/node_modules/openapi-codegen/node_modules/openapi-sampler/dist/openapi-sampler.js:582:43
    at Array.forEach (<anonymous>)
    at sampleObject (/Users/fabian/.nvm/versions/node/v10.9.0/lib/node_modules/openapi-codegen/node_modules/openapi-sampler/dist/openapi-sampler.js:576:36)

$ node --version
v10.9.0
$ npm --version
6.2.0
```

**Comment by MikeRalphson** [comment]
Thanks for the report and including the traceback. Will take a look.

**Comment by MikeRalphson** [comment]
`openapi-sampler` is used to generate examples where they are not already present from OpenAPI schemas. This module can't (yet) handle self-referential / circular schemas so it was blowing up.

I've added a `try/catch` around the use of `openapi-sampler` to prevent the crash.

Continued testing then showed up another couple of related issues. These should hopefully have been fixed by changing the way we clone objects.

Model generation may well not be perfect for recursive schemas - and probably it never will be, but at least the crashes should be gone.

Let me know how you get on with `v1.5.2`, and if any further problems, I'll reopen this issue.

**Comment by FabianFrank** [comment]
Thanks for the quick fix. It no longer crashes and outputs the code now. The error is printed as a warning, which I'm assuming is expected:
```
$ cg typescript-node ~/Downloads/swagger.yaml
{ level: 'Error',
  elementType: 'Context',
  elementId: '#/',
  message: 'Maximum call stack size exceeded' }
Sampler: Maximum call stack size exceeded
Sampler: Maximum call stack size exceeded
Sampler: Maximum call stack size exceeded
Sampler: Maximum call stack size exceeded
Sampler: Maximum call stack size exceeded
Sampler: Maximum call stack size exceeded
Sampler: Maximum call stack size exceeded
Sampler: Maximum call stack size exceeded
Sampler: Maximum call stack size exceeded
Sampler: Maximum call stack size exceeded
Sampler: Maximum call stack size exceeded
Sampler: Maximum call stack size exceeded
Sampler: Maximum call stack size exceeded
Sampler: Maximum call stack size exceeded
Sampler: Maximum call stack size exceeded
Sampler: Maximum call stack size exceeded
Sampler: Maximum call stack size exceeded
Sampler: Maximum call stack size exceeded
Sampler: Maximum call stack size exceeded
Sampler: Maximum call stack size exceeded
Sampler: Maximum call stack size exceeded
Sampler: Maximum call stack size exceeded
Sampler: Maximum call stack size exceeded
Sampler: Maximum call stack size exceeded
Sampler: Maximum call stack size exceeded
```
