### ISSUE TITLE
YAMLException: unacceptable kind of an object to dump [object Undefined]

### ISSUE THREAD

**Issue by DaLN** [Mermade/openapi-codegen#49]
Hi everyone i have an issue which prevent me from generating NodeJS code.

Here is my result, i wonder if it's related to me adding the security schemes.

~~~~
cg nodejs C:\Users\Nelson\StudioProjects\...\api\swagger\openapi.json -o C:\Users\Nelson\StudioP
rojects\000\api\swagger\api2 --verbose
Loaded config nodejs
Loaded definition C:\Users\Nelson\StudioProjects\000\api\swagger\openapi.json

C:\Users\Nelson\AppData\Roaming\npm\node_modules\openapi-codegen\node_modules\js-yaml\lib\js-yaml\dumper.js:754
      throw new YAMLException('unacceptable kind of an object to dump ' + type);
      ^
YAMLException: unacceptable kind of an object to dump [object Undefined]
    at writeNode (C:\Users\Nelson\AppData\Roaming\npm\node_modules\openapi-codegen\node_modules\js-yaml\lib\js-yaml\dumper.js:754:13)
    at writeBlockMapping (C:\Users\Nelson\AppData\Roaming\npm\node_modules\openapi-codegen\node_modules\js-yaml\lib\js-yaml\dumper.js:633:10)
    at writeNode (C:\Users\Nelson\AppData\Roaming\npm\node_modules\openapi-codegen\node_modules\js-yaml\lib\js-yaml\dumper.js:726:9)
    at writeBlockMapping (C:\Users\Nelson\AppData\Roaming\npm\node_modules\openapi-codegen\node_modules\js-yaml\lib\js-yaml\dumper.js:633:10)
    at writeNode (C:\Users\Nelson\AppData\Roaming\npm\node_modules\openapi-codegen\node_modules\js-yaml\lib\js-yaml\dumper.js:726:9)
    at writeBlockMapping (C:\Users\Nelson\AppData\Roaming\npm\node_modules\openapi-codegen\node_modules\js-yaml\lib\js-yaml\dumper.js:633:10)
    at writeNode (C:\Users\Nelson\AppData\Roaming\npm\node_modules\openapi-codegen\node_modules\js-yaml\lib\js-yaml\dumper.js:726:9)
    at dump (C:\Users\Nelson\AppData\Roaming\npm\node_modules\openapi-codegen\node_modules\js-yaml\lib\js-yaml\dumper.js:815:7)
    at Object.safeDump (C:\Users\Nelson\AppData\Roaming\npm\node_modules\openapi-codegen\node_modules\js-yaml\lib\js-yaml\dumper.js:821:10)
    at Object.transform (C:\Users\Nelson\AppData\Roaming\npm\node_modules\openapi-codegen\adaptor.js:707:32)
~~~~

Here is my JSON openapi 3 spec :
```json
{
  "openapi" : "3.0.0",
  "servers" : [ {
    "description" : "SwaggerHub API Auto Mocking",
    "url" : "https://virtserver.swaggerhub.com/000/000/1.0.0"
  } ],
  "info" : {
    "description" : "This is a simple API",
    "version" : "1.0.0",
    "title" : "Invoicing API",
    "contact" : {
      "email" : "000"
    },
    "license" : {
      "name" : "Apache 2.0",
      "url" : "http://www.apache.org/licenses/LICENSE-2.0.html"
    }
  },
  "tags" : [ {
    "name" : "admins",
    "description" : "Secured Admin-only calls"
  }, {
    "name" : "developers",
    "description" : "Operations available to regular developers"
  } ],
  "paths" : {
    "/invoices" : {
      "get" : {
        "tags" : [ "developers" ],
        "summary" : "list all invoices.",
        "security" : [ {
          "oAuth2Scheme" : [ "requester", "approver", "auditer" ]
        } ],
        "operationId" : "listInvoices",
        "description" : "Retrieves list of invoices\n",
        "parameters" : [ {
          "in" : "query",
          "name" : "searchString",
          "description" : "pass an optional search string for looking up inventory.",
          "required" : false,
          "schema" : {
            "type" : "string"
          }
        } ],
        "responses" : {
          "200" : {
            "description" : "search results matching criteria",
            "content" : {
              "application/json" : {
                "schema" : {
                  "type" : "array",
                  "items" : {
                    "oneOf" : [ {
                      "$ref" : "#/components/schemas/InvoiceItem"
                    }, {
                      "$ref" : "#/components/schemas/SalariesInvoiceItem"
                    }, {
                      "$ref" : "#/components/schemas/DoubleRechargingInvoiceItem"
                    } ]
                  }
                }
              }
            }
          },
          "400" : {
            "description" : "bad input parameter"
          }
        }
      },
      "post" : {
        "tags" : [ "developers" ],
        "summary" : "adds an invoice item",
        "security" : [ {
          "oAuth2Scheme" : [ "requester" ]
        } ],
        "operationId" : "addinvoice",
        "responses" : {
          "201" : {
            "description" : "invoice item created"
          },
          "400" : {
            "description" : "invalid input, object invalid"
          },
          "409" : {
            "description" : "an existing item already exists"
          }
        },
        "requestBody" : {
          "content" : {
            "multipart/form-data" : {
              "schema" : {
                "type" : "object",
                "properties" : {
                  "filename" : {
                    "type" : "array",
                    "items" : {
                      "type" : "string",
                      "format" : "binary"
                    }
                  },
                  "invoiceItem" : {
                    "oneOf" : [ {
                      "$ref" : "#/components/schemas/InvoiceItem"
                    }, {
                      "$ref" : "#/components/schemas/SalariesInvoiceItem"
                    }, {
                      "$ref" : "#/components/schemas/DoubleRechargingInvoiceItem"
                    } ]
                  }
                }
              }
            }
          },
          "description" : "Invoice item to add"
        }
      }
    },
    "/invoices/{id}" : {
      "summary" : "Represents an invoice",
      "description" : "This resource represents an individual invoice in the system. Each invoice is identified by a numeric `id`.\n",
      "parameters" : [ {
        "in" : "path",
        "name" : "id",
        "schema" : {
          "type" : "integer"
        },
        "required" : true,
        "description" : "Invoice ID."
      } ],
      "put" : {
        "tags" : [ "developers" ],
        "summary" : "Update an invoice item",
        "security" : [ {
          "oAuth2Scheme" : [ "requester" ]
        } ],
        "operationId" : "updinvoice",
        "responses" : {
          "200" : {
            "description" : "Invoice item updated."
          },
          "204" : {
            "description" : "No content"
          },
          "404" : {
            "description" : "ID not found."
          }
        },
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "$ref" : "#/components/schemas/InvoiceItem"
              }
            }
          },
          "description" : "Invoice item to add"
        }
      },
      "patch" : {
        "tags" : [ "developers" ],
        "summary" : "Change an invoice\\'s state",
        "security" : [ {
          "oAuth2Scheme" : [ "approver", "requester" ]
        } ],
        "operationId" : "patchinvoice",
        "description" : "Update an invoice to the system.",
        "responses" : {
          "204" : {
            "description" : "invoice item updated"
          },
          "404" : {
            "description" : "Resource not found."
          },
          "409" : {
            "description" : "Conflicting States."
          }
        },
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "type" : "object",
                "properties" : {
                  "oldState" : {
                    "type" : "string"
                  },
                  "newState" : {
                    "type" : "string"
                  },
                  "newOwner" : {
                    "type" : "string"
                  }
                }
              }
            }
          },
          "description" : "Invoice item to add"
        }
      }
    }
  },
  "components" : {
    "securitySchemes" : {
      "oAuth2Scheme" : {
        "type" : "oauth2",
        "description" : "This API uses OAuth 2 with the implicit grant flow. [More info](https://api.example.com/docs/auth)",
        "flows" : {
          "password" : {
            "tokenUrl" : "/oauth2/token",
            "scopes" : {
              "requester" : "Requester role",
              "approver" : "Approver role",
              "auditer" : "Audit role"
            }
          }
        }
      }
    },
    "schemas" : {
      "InvoiceItem" : {
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "integer",
            "readOnly" : true
          },
          "originalInvoiceReferenceNumber" : {
            "type" : "integer",
            "example" : "001"
          },
          "invoiceFromDetails" : {
            "$ref" : "#/components/schemas/InvoiceFromDetails"
          },
          "doubleReinvoicing" : {
            "type" : "boolean"
          },
          "entityToBeReinvoiced" : {
            "$ref" : "#/components/schemas/EntityToBeReinvoiced"
          },
          "reinvoicingDescription" : {
            "$ref" : "#/components/schemas/RechargingInvoiceDescription"
          },
          "rechargingInvoiceAmount" : {
            "$ref" : "#/components/schemas/RechargingInvoiceAmount"
          },
          "note" : {
            "type" : "string"
          }
        },
        "required" : [ "id", "originalInvoiceReferenceNumber", "invoiceFromDetails", "doubleReinvoicing", "reinvoicingDescription", "rechargingInvoiceAmount" ]
      },
      "SalariesInvoiceItem" : {
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "integer",
            "readOnly" : true
          },
          "originalInvoiceReferenceNumber" : {
            "type" : "integer",
            "example" : "001"
          },
          "invoiceFromDetails" : {
            "$ref" : "#/components/schemas/InvoiceFromDetails"
          },
          "doubleReinvoicing" : {
            "type" : "boolean"
          },
          "entityToBeReinvoiced" : {
            "$ref" : "#/components/schemas/EntityToBeReinvoiced"
          },
          "reinvoicingDescription" : {
            "$ref" : "#/components/schemas/RechargingInvoiceDescription"
          },
          "salariesDetails" : {
            "$ref" : "#/components/schemas/SalariesDetails"
          },
          "note" : {
            "type" : "string"
          }
        },
        "required" : [ "id", "originalInvoiceReferenceNumber", "invoiceFromDetails", "reinvoicingDescription", "doubleReinvoicing", "entityToBeReinvoiced", "salariesDetails", "note" ]
      },
      "DoubleRechargingInvoiceItem" : {
        "type" : "object",
        "properties" : {
          "id" : {
            "type" : "integer",
            "readOnly" : true
          },
          "originalInvoiceReferenceNumber" : {
            "type" : "integer",
            "example" : "001"
          },
          "invoiceFromDetails" : {
            "$ref" : "#/components/schemas/InvoiceFromDetails"
          },
          "doubleReinvoicing" : {
            "type" : "boolean"
          },
          "intermediaryEntity" : {
            "$ref" : "#/components/schemas/IntermediaryEntity"
          },
          "entityToBeReinvoiced" : {
            "$ref" : "#/components/schemas/EntityToBeReinvoiced"
          },
          "reinvoicingDescription" : {
            "$ref" : "#/components/schemas/RechargingInvoiceDescription"
          },
          "rechargingInvoiceAmount" : {
            "$ref" : "#/components/schemas/RechargingInvoiceAmount"
          },
          "salariesDetails" : {
            "$ref" : "#/components/schemas/SalariesDetails"
          },
          "note" : {
            "type" : "string"
          }
        },
        "required" : [ "id", "originalInvoiceReferenceNumber", "invoiceFromDetails", "doubleReinvoicing", "intermediaryEntity", "entityToBeReinvoiced", "reinvoicingDescription", "rechargingInvoiceAmount", "salariesDetails", "note" ]
      },
      "InvoiceFromDetails" : {
        "type" : "object",
        "properties" : {
          "entityDescription" : {
            "type" : "string",
            "example" : "Coordination France - 0034"
          },
          "hfmEntityCode" : {
            "type" : "string",
            "example" : "0034"
          },
          "accountingContact" : {
            "type" : "string",
            "example" : "Accountant #42"
          },
          "requester" : {
            "type" : "string",
            "example" : "Lee-Anne"
          },
          "department" : {
            "type" : "string",
            "example" : "Name Of Department"
          },
          "departmentManager" : {
            "type" : "string",
            "example" : "N+1"
          },
          "costCenter" : {
            "type" : "string"
          }
        },
        "required" : [ "entityDescription", "hfmEntityCode", "accountingContact", "requester", "department", "departmentManager", "costCenter" ]
      },
      "IntermediaryEntity" : {
        "type" : "object",
        "properties" : {
          "entityDescription" : {
            "type" : "string",
            "example" : "Description of the Entity"
          },
          "hfmEntityCode" : {
            "type" : "string",
            "example" : "0141"
          },
          "contactName" : {
            "type" : "string",
            "example" : "Contact's name"
          }
        },
        "required" : [ "entityDescription", "hfmEntityCode", "contactName" ]
      },
      "EntityToBeReinvoiced" : {
        "type" : "object",
        "properties" : {
          "entityDescription" : {
            "type" : "string",
            "example" : "Description of the Entity"
          },
          "hemEntityCode" : {
            "type" : "string",
            "example" : "0141"
          },
          "costCenter" : {
            "type" : "string",
            "example" : "Cost Center Name"
          },
          "commercialDepartment" : {
            "type" : "string",
            "example" : "Type Department"
          },
          "commercialDepartmentManager" : {
            "type" : "string",
            "example" : "Manager's name"
          },
          "contactName" : {
            "type" : "string",
            "example" : "Contact's name"
          }
        },
        "required" : [ "entityDescription", "hemEntityCode", "costCenter", "commercialDepartment", "commercialDepartmentManager", "contactName" ]
      },
      "RechargingInvoiceDescription" : {
        "type" : "object",
        "properties" : {
          "projectName" : {
            "type" : "string",
            "example" : "Project Name"
          },
          "reinvoiceDescription" : {
            "type" : "string",
            "example" : "Description"
          },
          "invoiceType" : {
            "type" : "string",
            "example" : "Type O Negative"
          },
          "transferPricingCategory" : {
            "type" : "string",
            "example" : "Cat 42"
          },
          "recurring" : {
            "type" : "boolean"
          },
          "expenseBasedOn" : {
            "type" : "string",
            "example" : "Something"
          },
          "amountIs" : {
            "type" : "string",
            "example" : "Something"
          },
          "relatedToHeadcountStaffCosts" : {
            "type" : "boolean"
          }
        },
        "required" : [ "projectName", "reinvoiceDescription", "invoiceType", "transferPricingCategory", "recurring", "expenseBasedOn", "amountIs", "relatedToHeadcountStaffCosts" ]
      },
      "RechargingInvoiceAmount" : {
        "type" : "object",
        "properties" : {
          "currency" : {
            "type" : "string",
            "example" : "USD"
          },
          "amountLines" : {
            "type" : "array",
            "items" : {
              "$ref" : "#/components/schemas/AmountLine"
            }
          },
          "markUp" : {
            "type" : "number",
            "format" : "float"
          },
          "totalWithoutVAT" : {
            "type" : "number",
            "format" : "float"
          },
          "vat" : {
            "type" : "number",
            "format" : "float"
          },
          "totalWithVAT" : {
            "type" : "number",
            "format" : "float"
          }
        },
        "required" : [ "currency" ]
      },
      "AmountLine" : {
        "type" : "object",
        "properties" : {
          "itemCode" : {
            "type" : "string",
            "example" : "Code 007"
          },
          "itemDescription" : {
            "type" : "string",
            "example" : "Description"
          },
          "quantity" : {
            "type" : "integer"
          },
          "pricePerUnit" : {
            "type" : "number",
            "format" : "float"
          },
          "globalSCOA" : {
            "type" : "string",
            "example" : "GlobalSCOA"
          },
          "localAccount" : {
            "type" : "string",
            "example" : "Receiving Entity"
          },
          "itemTotal" : {
            "type" : "number",
            "format" : "float"
          }
        },
        "required" : [ "itemCode", "itemDescription", "quantity", "pricePerUnit", "globalSCOA", "localAccount", "itemTotal" ]
      },
      "SalariesDetails" : {
        "type" : "object",
        "properties" : {
          "department" : {
            "type" : "string",
            "example" : "R&D"
          },
          "employeesName" : {
            "type" : "string",
            "example" : "Bob Burnquist, Alain Dupont"
          },
          "currency" : {
            "type" : "string",
            "example" : "GBP"
          },
          "headcount" : {
            "type" : "integer"
          },
          "salaries" : {
            "type" : "number",
            "format" : "float"
          },
          "pensionCosts" : {
            "type" : "number",
            "format" : "float"
          },
          "profitSharing" : {
            "type" : "number",
            "format" : "float"
          },
          "socialCharges" : {
            "type" : "number",
            "format" : "float"
          },
          "healthAndLifeInsurance" : {
            "type" : "number",
            "format" : "float"
          },
          "relocationAllowance" : {
            "type" : "number",
            "format" : "float"
          },
          "companyCar" : {
            "type" : "number",
            "format" : "float"
          },
          "clothingAllowance" : {
            "type" : "number",
            "format" : "float"
          },
          "travelAndEntertainment" : {
            "type" : "number",
            "format" : "float"
          },
          "consulting" : {
            "type" : "number",
            "format" : "float"
          },
          "other" : {
            "type" : "number",
            "format" : "float"
          },
          "markUp" : {
            "type" : "integer"
          },
          "total" : {
            "type" : "number",
            "format" : "float"
          }
        },
        "required" : [ "department", "employeesName", "currency", "headcount" ]
      }
    }
  }
}```

**Comment by MikeRalphson** [comment]
`v1.5.4` contains the latest version of the OpenAPI 3.0.x to Swagger 2.0 down-conversion code. Hopefully that should fix it for you.

**Comment by DaLN** [comment]
Thanks, will test that out.

**Comment by DaLN** [comment]
Got a similar error 

> C:\Users\Nelson\AppData\Roaming\npm\node_modules\openapi-codegen\node_modules\js-yaml\lib\js-yaml\dumper.js:754
      throw new YAMLException('unacceptable kind of an object to dump ' + type);
      ^
YAMLException: unacceptable kind of an object to dump [object Undefined]
    at writeNode (C:\Users\Nelson\AppData\Roaming\npm\node_modules\openapi-codegen\node_modules\js-yaml\lib\js-yaml\dumper.js:754:13)
    at writeBlockMapping (C:\Users\Nelson\AppData\Roaming\npm\node_modules\openapi-codegen\node_modules\js-yaml\lib\js-yaml\dumper.js:633:10)
    at writeNode (C:\Users\Nelson\AppData\Roaming\npm\node_modules\openapi-codegen\node_modules\js-yaml\lib\js-yaml\dumper.js:726:9)
    at writeBlockMapping (C:\Users\Nelson\AppData\Roaming\npm\node_modules\openapi-codegen\node_modules\js-yaml\lib\js-yaml\dumper.js:633:10)
    at writeNode (C:\Users\Nelson\AppData\Roaming\npm\node_modules\openapi-codegen\node_modules\js-yaml\lib\js-yaml\dumper.js:726:9)
    at writeBlockMapping (C:\Users\Nelson\AppData\Roaming\npm\node_modules\openapi-codegen\node_modules\js-yaml\lib\js-yaml\dumper.js:633:10)
    at writeNode (C:\Users\Nelson\AppData\Roaming\npm\node_modules\openapi-codegen\node_modules\js-yaml\lib\js-yaml\dumper.js:726:9)
    at dump (C:\Users\Nelson\AppData\Roaming\npm\node_modules\openapi-codegen\node_modules\js-yaml\lib\js-yaml\dumper.js:815:7)
    at Object.safeDump (C:\Users\Nelson\AppData\Roaming\npm\node_modules\openapi-codegen\node_modules\js-yaml\lib\js-yaml\dumper.js:821:10)
    at Object.transform (C:\Users\Nelson\AppData\Roaming\npm\node_modules\openapi-codegen\adaptor.js:707:32)

**Comment by DaLN** [comment]
Got a similar error :
~~~~
cg nodejs C:\Users\Nelson\StudioProjects\000\api\swagger\openapi.j
son -o C:\Users\Nelson\StudioProjects\000\api\swagger\000api2 --verbose
Loaded config nodejs
Loaded definition C:\Users\Nelson\StudioProjects\000\api\swagger\openapi.json

 C:\Users\Nelson\AppData\Roaming\npm\node_modules\openapi-codegen\node_modules\js-yaml\lib\js-yaml\dumper.js:754

      throw new YAMLException('unacceptable kind of an object to dump ' + type);
      ^
YAMLException: unacceptable kind of an object to dump [object Undefined]
    at writeNode (C:\Users\Nelson\AppData\Roaming\npm\node_modules\openapi-codegen\node_modules\js-yaml\lib\js-yaml\dumper.js:754:13)
    at writeBlockMapping (C:\Users\Nelson\AppData\Roaming\npm\node_modules\openapi-codegen\node_modules\js-yaml\lib\js-yaml\dumper.js:633:10)
    at writeNode (C:\Users\Nelson\AppData\Roaming\npm\node_modules\openapi-codegen\node_modules\js-yaml\lib\js-yaml\dumper.js:726:9)
    at writeBlockMapping (C:\Users\Nelson\AppData\Roaming\npm\node_modules\openapi-codegen\node_modules\js-yaml\lib\js-yaml\dumper.js:633:10)
    at writeNode (C:\Users\Nelson\AppData\Roaming\npm\node_modules\openapi-codegen\node_modules\js-yaml\lib\js-yaml\dumper.js:726:9)
    at writeBlockMapping (C:\Users\Nelson\AppData\Roaming\npm\node_modules\openapi-codegen\node_modules\js-yaml\lib\js-yaml\dumper.js:633:10)
    at writeNode (C:\Users\Nelson\AppData\Roaming\npm\node_modules\openapi-codegen\node_modules\js-yaml\lib\js-yaml\dumper.js:726:9)
    at dump (C:\Users\Nelson\AppData\Roaming\npm\node_modules\openapi-codegen\node_modules\js-yaml\lib\js-yaml\dumper.js:815:7)
    at Object.safeDump (C:\Users\Nelson\AppData\Roaming\npm\node_modules\openapi-codegen\node_modules\js-yaml\lib\js-yaml\dumper.js:821:10)
    at Object.transform (C:\Users\Nelson\AppData\Roaming\npm\node_modules\openapi-codegen\adaptor.js:707:32)
~~~~

**Comment by Cruaier** [comment]
@MikeRalphson I'm getting the same error using a yaml file and the most current version.
The stacktrace doesn't help much..

**Comment by MikeRalphson** [comment]
@DaLN, @Cruaier please re-test with the latest (`v1.5.5`). This *should* no longer happen.

**Comment by MikeRalphson** [comment]
Closing due to inactivity - but please feel free to reopen the issue if necessary.
