### ISSUE TITLE
Error: Cannot find module 'js-yaml'

### ISSUE THREAD

**Issue by Asheq** [Mermade/openapi-codegen#7]
I get the following error when running the example. Any help is much appreciated!
    
    $ node cg --verbose nodejs defs/generator.yaml
    module.js:529
        throw err;
        ^

    Error: Cannot find module 'js-yaml'
        at Function.Module._resolveFilename (module.js:527:15)
        at Function.Module._load (module.js:476:23)
        at Module.require (module.js:568:17)
        at require (internal/module.js:11:18)
        at Object.<anonymous> (/Users/asheqimran/Development/github.com/Mermade/openapi-codegen/cg.js:8:14)
        at Module._compile (module.js:624:30)
        at Object.Module._extensions..js (module.js:635:10)
        at Module.load (module.js:545:32)
        at tryModuleLoad (module.js:508:12)
        at Function.Module._load (module.js:500:3)

**Comment by MikeRalphson** [comment]
Have you done `npm i` (or the `yarn` equivalent) to install the dependencies? I probably need to add an 'installing' section to the `README.md`.

**Comment by Asheq** [comment]
Ahh, of course. That was the problem. Thanks!
